/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#a8004b",
        "surface-container-lowest": "#0e0e11",
        "on-background": "#e4e1e6",
        "secondary-container": "#00e3fd",
        "surface-bright": "#39393c",
        "on-secondary-fixed": "#001f24",
        "surface-dim": "#131316",
        "surface-container": "#1f1f22",
        "on-tertiary-fixed": "#3f0018",
        "inverse-primary": "#6833ea",
        "outline": "#948da2",
        "on-primary-fixed-variant": "#4f00d0",
        "surface-container-highest": "#353438",
        "on-tertiary-fixed-variant": "#8f003f",
        "surface-container-high": "#2a2a2d",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "surface": "#131316",
        "on-primary-fixed": "#20005f",
        "outline-variant": "#494456",
        "primary-container": "#5d21df",
        "on-primary": "#370096",
        "primary": "#cdbdff",
        "on-secondary-fixed-variant": "#004f58",
        "inverse-on-surface": "#303033",
        "tertiary-fixed": "#ffd9df",
        "background": "#131316",
        "secondary": "#bdf4ff",
        "on-surface": "#e4e1e6",
        "on-tertiary": "#66002a",
        "surface-tint": "#cdbdff",
        "tertiary-fixed-dim": "#ffb1c1",
        "on-primary-container": "#cebfff",
        "surface-container-low": "#1b1b1e",
        "secondary-fixed": "#9cf0ff",
        "secondary-fixed-dim": "#00daf3",
        "on-secondary": "#00363d",
        "on-surface-variant": "#cbc3d9",
        "on-secondary-container": "#00616d",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "primary-fixed-dim": "#cdbdff",
        "inverse-surface": "#e4e1e6",
        "on-tertiary-container": "#ffb4c3",
        "tertiary": "#ffb1c1",
        "primary-fixed": "#e8deff",
        "surface-variant": "#353438"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
